# Generated by Django 3.2.7 on 2021-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filepost', models.FileField(upload_to='')),
                ('Title', models.CharField(max_length=500)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User', models.CharField(max_length=500)),
                ('id_Blog', models.CharField(max_length=500)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Birthday', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio', models.CharField(max_length=500)),
                ('El', models.CharField(max_length=500)),
                ('vi', models.CharField(max_length=500)),
                ('ExEl', models.CharField(max_length=500)),
                ('ExVi', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=500)),
                ('A', models.CharField(max_length=500)),
                ('B', models.CharField(max_length=500)),
                ('C', models.CharField(max_length=500)),
                ('D', models.CharField(max_length=500)),
                ('Answer', models.CharField(max_length=2)),
                ('Skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudiVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=300)),
            ],
        ),
    ]
