# Generated by Django 3.2.7 on 2021-11-17 06:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamCourse', models.CharField(default='', max_length=500)),
                ('SizeCourse', models.CharField(default='', max_length=100)),
                ('ListIdVideo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='parentId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id_Blog',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id_User',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='ExEl',
        ),
        migrations.AddField(
            model_name='blog',
            name='Summary',
            field=models.CharField(default="If you previously created a superuser for Django's Admin web app then you might need to create the user again.", max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='blogId',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='FaCourse',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='MyCourse',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='Sex',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='ExEla',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='ExElb',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='syn',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studivideo',
            name='Themes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Filepost',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='Audio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='El',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='ExVi',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='vi',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='A',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Answer',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='B',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='C',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='D',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Question',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Skill',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studivideo',
            name='Title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studivideo',
            name='Video',
            field=models.CharField(default='', max_length=500),
        ),
    ]
