# Generated by Django 3.2.7 on 2021-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20211117_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mc',
            new_name='Mcourses',
        ),
    ]
