# Generated by Django 3.2.7 on 2021-11-17 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_rename_mc_mcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamCourse', models.CharField(default='', max_length=500)),
                ('SizeCourse', models.CharField(default='', max_length=100)),
                ('ListIdVideo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Mcourses',
        ),
    ]
