# Generated by Django 3.2.7 on 2021-11-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20211117_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourses',
            old_name='NamC',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='mycourses',
            old_name='ListIdVideo',
            new_name='listarray',
        ),
        migrations.RenameField(
            model_name='mycourses',
            old_name='SizeC',
            new_name='size',
        ),
    ]
