# Generated by Django 3.2.7 on 2021-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20211117_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='skill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
