# Generated by Django 3.2.7 on 2021-11-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_mycourses_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourses',
            name='listarray',
        ),
        migrations.RemoveField(
            model_name='mycourses',
            name='size',
        ),
        migrations.RemoveField(
            model_name='mycourses',
            name='skill',
        ),
    ]
