# Generated by Django 3.2.7 on 2021-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_auto_20211121_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='Price',
            field=models.CharField(default='', max_length=500),
        ),
    ]
