# Generated by Django 3.2.7 on 2021-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_alter_mycourses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='Price',
            field=models.FloatField(default='0', max_length=500),
        ),
    ]
