# Generated by Django 3.2.7 on 2021-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_alter_mycourses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='Price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
