# Generated by Django 3.2.7 on 2021-11-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_alter_mycourses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourses',
            name='Prices',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='mycourses',
            name='Price',
            field=models.CharField(default='', max_length=500),
        ),
    ]
