# Generated by Django 3.2.7 on 2021-11-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_auto_20211130_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourses',
            name='Prices',
        ),
    ]
