# Generated by Django 3.2.7 on 2021-11-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0016_remove_mycourses_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FaCourse',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='MyCourse',
        ),
    ]
