# Generated by Django 3.2.7 on 2021-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_auto_20211130_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='Price',
            field=models.FloatField(null=True),
        ),
    ]
